name: Generate CLASPRC_JSON

on:
  workflow_dispatch: # ブラウザから手動実行できるようにする設定

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Print Login Instructions
        run: |
          echo "以下のURLをブラウザで開き、所有者アカウントでログインして認可コードを取得してください。"
          npx @google/clasp login --no-localhost
